In [1]:
list1=[1,2,3,4]
list2=[2,3,4,5]
list1+list2

[1, 2, 3, 4, 2, 3, 4, 5]

In [2]:
for i,j in zip(list1,list2):
    print(i+j)

3
5
7
9


In [3]:
list3=[]
for i,j in zip(list1,list2):
    list3.append(i+j)
print(list3)

[3, 5, 7, 9]


# numpy

In [4]:
import numpy as np
print(np.array(list1))

[1 2 3 4]


In [5]:
arr1=np.array(list1)
print(arr1)

[1 2 3 4]


In [6]:
arr1

array([1, 2, 3, 4])

In [7]:
arr2=np.array(list2)
arr2

array([2, 3, 4, 5])

In [9]:
sum1=arr1+arr2
sum1

array([3, 5, 7, 9])

In [10]:
%whos

Variable   Type       Data/Info
-------------------------------
arr1       ndarray    4: 4 elems, type `int32`, 16 bytes
arr2       ndarray    4: 4 elems, type `int32`, 16 bytes
i          int        4
j          int        5
list1      list       n=4
list2      list       n=4
list3      list       n=4
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
sum1       ndarray    4: 4 elems, type `int32`, 16 bytes


In [11]:
data2=[[1,2,3,4],[5,6,7,8]]
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [12]:
arr3=np.array(data2)
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr3.ndim

2

In [14]:
arr3.dtype

dtype('int32')

In [15]:
arr3.shape

(2, 4)

In [16]:
arr4=np.array(data2,dtype=float)
arr4

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [17]:
arr4.dtype

dtype('float64')

In [18]:
arr5=np.array(['1','2','3','5'])
arr5

array(['1', '2', '3', '5'], dtype='<U1')

In [19]:
arr6=np.array(arr5,dtype=int)
arr6

array([1, 2, 3, 5])

In [20]:
arr6.dtype

dtype('int32')

In [21]:
list(range(7))

[0, 1, 2, 3, 4, 5, 6]

In [22]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [23]:
arr7=np.arange(4,20)
arr7

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
arr8=np.arange(4,20,2)
arr8

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
arr9=arr8.reshape(4,2)
arr9

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [26]:
arr10=arr9.reshape(2,4)

In [27]:
arr10

array([[ 4,  6,  8, 10],
       [12, 14, 16, 18]])

In [29]:
arr11=np.linspace(1,30,5)
arr11

array([ 1.  ,  8.25, 15.5 , 22.75, 30.  ])

In [30]:
arr12=np.linspace(1,12,4)
arr12

array([ 1.        ,  4.66666667,  8.33333333, 12.        ])

In [33]:
arr=np.arange(5,20)
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
arr[5:12]

array([10, 11, 12, 13, 14, 15, 16])

In [35]:
arr[5]

10

In [36]:
arr[5:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
arr[:5]

array([5, 6, 7, 8, 9])

In [40]:
arr[1,3,5]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [41]:
arr[[1,3,5]]

array([ 6,  8, 10])

In [43]:
arr13=np.array([[-7,5,-2,4],[5,2,7,3],[-13,10,3,-5]])
arr13

array([[ -7,   5,  -2,   4],
       [  5,   2,   7,   3],
       [-13,  10,   3,  -5]])

In [44]:
arr13[2]

array([-13,  10,   3,  -5])

In [45]:
arr13[0]

array([-7,  5, -2,  4])

In [47]:
arr13[[0,2]]

array([[ -7,   5,  -2,   4],
       [-13,  10,   3,  -5]])

In [49]:
arr13[:,1]

array([ 5,  2, 10])

In [50]:
arr13[1,1]

2

In [51]:
arr14=np.arange(10,82,2)
arr14

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80])

In [53]:
len(arr14)

36

In [54]:
arr14=arr14.reshape(6,6)
arr14

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

# To get multiple particular coloumns

In [56]:
#To get coloumn having 0th index and 2nd index
arr14[:,[0,2]]

array([[10, 14],
       [22, 26],
       [34, 38],
       [46, 50],
       [58, 62],
       [70, 74]])

In [57]:
#To get coloumn from 0th index to 2nd index 
arr14[:,0:2]

array([[10, 12],
       [22, 24],
       [34, 36],
       [46, 48],
       [58, 60],
       [70, 72]])

In [59]:
# we get 1st 3 rows
arr14[:3,:]

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44]])

# Built in functions

In [60]:
# to get sum
arr15=np.array([38,40,42,50])
arr15.sum()

170

In [61]:
# using built in function in numpy
np.sum(arr15)

170

In [62]:
# Mean function
arr15.mean()

42.5

In [63]:
np.mean(arr15)

42.5

In [64]:
# array have no median function
arr15.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [65]:
#numpy have the median function
np.median(arr15)

41.0

In [67]:
arr15=arr15.reshape(2,2)
arr15

array([[38, 40],
       [42, 50]])

In [68]:
arr15.sum()

170

# To get sum of particula row or coloumn

In [69]:
# to get sum along the x axis, ie. taking sum of elements in row wise manner
arr15.sum(axis=1)

array([78, 92])

In [70]:
# to get sum along the y axis. ie, taking sum of elements in coloumn wise manner
arr15.sum(axis=0)

array([80, 90])

In [71]:
arr15.sum(1)

array([78, 92])

In [72]:
arr15.sum(0)

array([80, 90])

# Scalar operation

In [73]:
arr14

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78, 80]])

In [74]:
arr14+5

array([[15, 17, 19, 21, 23, 25],
       [27, 29, 31, 33, 35, 37],
       [39, 41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59, 61],
       [63, 65, 67, 69, 71, 73],
       [75, 77, 79, 81, 83, 85]])

In [75]:
arr14-5

array([[ 5,  7,  9, 11, 13, 15],
       [17, 19, 21, 23, 25, 27],
       [29, 31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49, 51],
       [53, 55, 57, 59, 61, 63],
       [65, 67, 69, 71, 73, 75]])

In [76]:
arr14*5

array([[ 50,  60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150, 160],
       [170, 180, 190, 200, 210, 220],
       [230, 240, 250, 260, 270, 280],
       [290, 300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390, 400]])

In [77]:
arr14/5

array([[ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ],
       [ 4.4,  4.8,  5.2,  5.6,  6. ,  6.4],
       [ 6.8,  7.2,  7.6,  8. ,  8.4,  8.8],
       [ 9.2,  9.6, 10. , 10.4, 10.8, 11.2],
       [11.6, 12. , 12.4, 12.8, 13.2, 13.6],
       [14. , 14.4, 14.8, 15.2, 15.6, 16. ]])

In [79]:
# replace all the value in index 5 of row with -9
arr14[5]=-9
arr14

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [-9, -9, -9, -9, -9, -9]])

In [80]:
# To get absolute value
np.abs(arr14)

array([[10, 12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44],
       [46, 48, 50, 52, 54, 56],
       [58, 60, 62, 64, 66, 68],
       [ 9,  9,  9,  9,  9,  9]])

In [82]:
arr14=np.abs(arr14)

In [84]:
np.sqrt(arr14)

array([[3.16227766, 3.46410162, 3.74165739, 4.        , 4.24264069,
        4.47213595],
       [4.69041576, 4.89897949, 5.09901951, 5.29150262, 5.47722558,
        5.65685425],
       [5.83095189, 6.        , 6.164414  , 6.32455532, 6.4807407 ,
        6.63324958],
       [6.78232998, 6.92820323, 7.07106781, 7.21110255, 7.34846923,
        7.48331477],
       [7.61577311, 7.74596669, 7.87400787, 8.        , 8.1240384 ,
        8.24621125],
       [3.        , 3.        , 3.        , 3.        , 3.        ,
        3.        ]])

In [85]:
type(arr14)

numpy.ndarray

In [86]:
# to get an array full of zeros
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [89]:
#to get an array full of ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
# to get an identity matix. single bracket is enough unlike ones and zeros
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Dot product(Matrix multiplication)

In [91]:
A=np.arange(8).reshape(2,4)
B=np.arange(8).reshape(4,2)
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [92]:
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [93]:
# for dot product, number of coloumns of first array equal to no. of rows of 2nd matrix
A.dot(B)

array([[28, 34],
       [76, 98]])

In [94]:
#Transpose of a matrix(ie, interchanging rows and coloumns)
arr14.T

array([[10, 22, 34, 46, 58,  9],
       [12, 24, 36, 48, 60,  9],
       [14, 26, 38, 50, 62,  9],
       [16, 28, 40, 52, 64,  9],
       [18, 30, 42, 54, 66,  9],
       [20, 32, 44, 56, 68,  9]])